### ISSUE TITLE
Windows color support using DefaultConsoleOptions

### ISSUE THREAD

**Issue by d-tsuji** [nsf/jsondiff#7]
Thank you for this library. I am a Windows user.

I would like to improve the display of special characters with color on Windows. when I install this library in a Windows environment and use `jsondiff.DefaultConsoleOptions()` to display the diff, if the diff is present, it looks like this.

```bash
        , want=[
          {
            "user_id": "001",
            "name": "gopher"
          },
          {
            "user_id": "002",
            "name": "rubyist"
          }
        ]
        , diff=[
            {
                "name": ?[0;33m"rubyist" => "gopher"?[0m,
                "user_id": ?[0;33m"002" => "001"?[0m
            },
            {
                "name": "rubyist",
                "user_id": "002"
            }
        ]
```

Strings like `?[0;33m` and `?[0m` are hard to see.

**Comment by nsf** [comment]
Yeah, sorry about that. It's probably best to call this "DefaultTerminalOptions()", as it uses terminal escape sequences for colors. In any case for now you can just provide your own options:

https://github.com/nsf/jsondiff/blob/f29ed568f4cee6cbc273a4c11dc332141d75196a/jsondiff.go#L69-L77

If you change Begin/End to empty strings, it shouldn't show those weird symbols. But you're right, ideally I should apply some windows specific tweak, so that default looks good on windows. Have no idea when it'll be done.

**Comment by d-tsuji** [comment]
Thanks for the reply. 

```go
package d

import (
	"encoding/json"
	"testing"

	"github.com/nsf/jsondiff"
)

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func TestDiff(t *testing.T) {
	want := `{"name": "gopher", "xxx": "yyy"}`
	u := User{Name: "rubyist"}
	got, _ := json.Marshal(u)

	opt := jsondiff.DefaultConsoleOptions()
	opt.Added.Begin = ""
	opt.Added.End = ""
	opt.Removed.Begin = ""
	opt.Removed.End = ""
	opt.Changed.Begin = ""
	opt.Changed.End = ""

	if d, s := jsondiff.Compare(got, []byte(want), &opt); d != jsondiff.FullMatch {
		t.Errorf("unmatch, got=%s, want=%s, diff=%s", got, want, s)
	}
}
```

It is true that the special characters are no longer printed when I specify an empty string, as shown below. I felt the disadvantage is that it makes it difficult to see the difference.

- output

```bash
> go test -v
=== RUN   TestDiff
    diff_test.go:29: unmatch, got={"id":"","name":"rubyist"}, want={"name": "gopher", "xxx": "yyy"}, diff={
            "id": "",
            "name": "rubyist" => "gopher",
            "xxx": "yyy"
        }
--- FAIL: TestDiff (0.00s)
FAIL
exit status 1
FAIL    github.com/d-tsuji/go-sandbox/d 0.158s
```

---

Ideally, the output should look like this, but I understand that it may be difficult. Thanks.

![image](https://user-images.githubusercontent.com/24369487/93867263-c3354980-fd03-11ea-8a21-2391f8ff2317.png)

**Comment by nsf** [comment]
I'm not actually sure if it's possible to control character colors on windows with just text output. You might try some solutions from the internet: 
https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences
https://gist.github.com/mlocati/fdabcaeb8071d5c75a2d51712db24011

I would gladly try some of these, but I'm not sure when I will actually be on my windows 10 machine in dev mode. Don't do much development under windows (only play games there).

**Comment by d-tsuji** [comment]
Well, `Fprintf` and [mattn/go-colorable](https://github.com/mattn/go-colorable), it is possible to make the library colorable on the user's side.

But `t.Logf` and `t.Log` cannot be used because the output destination cannot be set.

For now, this method seems to be the best. Because `jsondiff.Compare` is an API that returns a diff string as its second argument.

---

```go
package d

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/mattn/go-colorable"
	"github.com/nsf/jsondiff"
)

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func TestDiff(t *testing.T) {
	want := `{"name": "gopher", "xxx": "yyy"}`
	u := User{Name: "rubyist"}
	got, _ := json.Marshal(u)

	opt := jsondiff.DefaultConsoleOptions()

	if d, diff := jsondiff.Compare(got, []byte(want), &opt); d != jsondiff.FullMatch {
		t.Errorf("unmatch, got=%s, want=%s", got, want)
		w := colorable.NewColorableStderr()
		fmt.Fprintf(w, fmt.Sprintf("diff: %s", diff))
	}
}
```

- output

![image](https://user-images.githubusercontent.com/24369487/93875283-ac94ef80-fd0f-11ea-917d-20ec74c0a637.png)

**Comment by d-tsuji** [comment]
There was a way to make it more colorful in the meantime, so this Issue is closed. Thank you!
