### ISSUE TITLE
Allow use of an epsilon when comparing numeric values

### ISSUE THREAD

**Issue by psFried** [nsf/jsondiff#9]
We'd like to use jsondiff for comparing JSON that is output from some computation to a static "expected" JSON object. This raises the problem of how to handle floating point numbers. For example, if you run `30.33 - 29 - 0.33` you may get a result something like `0.9999999999999982`, which we would like to consider the same as an "expected" value of `1.0`. 

The current behavior is for jsondiff to compare the original string representations of numeric values. This may be a reasonable default behavior for a generic json library like this, and is certainly the "right" method for some use cases. Additionally, comparisons using an epsilon are impossible to generalize for all use cases, since the optimal epsilon value may depend on the relative scale of the numbers that were used to produce the final result (e.g. `2.3 - 1.2` vs `2.3e10 - 2.29999999988e10`).  So I think it makes sense to make the use of floats optional.

A related issue with using the string representation for comparisons is that the exact same numeric value can be represented in different ways. For example, the current behavior considers `1` and `1.0` to be different. Same goes for `1e10` and `10e2`. So the proposal is for these cases to also be considered the same when using floats.

**Comment by nsf** [comment]
I understand the need, but I'll implement it myself in a way that hopefully suits your needs as well. Will add 
```go
CompareNumbers func(a, b json.Number) bool
```
to Options, and when provided this function will control how numbers are compared. I used your test code though, hopefully you don't mind. See: https://github.com/nsf/jsondiff/commit/6ea32392771e7b92c36671ce0ca29e11a063fa44.

Feel free to close the issue if it works for you.

**Comment by psFried** [comment]
Yep, that works. Thanks!
